config/routes.rb
ShakaCompany::Application.routes.draw do
  resources :rent_payments

  get "static_pages/home"

  resources :fuel_payments

  resources :fuel_refills

  resources :accounts

  resources :expenses

  resources :repairs

  resources :jobs

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/fuel_refill.rb
class FuelRefill < ActiveRecord::Base
  
  attr_accessible :account, :subaccount, :amount, :litres, :other_purchases, :price, :receipt_number, :station, :vehicle_number, :order_number, :refill_date
  has_paper_trail
  def account_enum
	['Shaka Company', 'Shaka Augustine']
  end
  def subaccount_enum
	['Kateso', 'Singa', 'Twebaze', 'Rogers Kabaco', 'Ruhweza', 'Fred', 'Sowedi', 'Mukobi', 'Mukobi-Twebaze', 'Mukobi-Fred', 'Other']
  end
end

app/controllers/fuel_refills_controller.rb
class FuelRefillsController < ApplicationController
  # GET /fuel_refills
  # GET /fuel_refills.json
  def index
    @fuel_refills = FuelRefill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fuel_refills }
    end
  end

  # GET /fuel_refills/1
  # GET /fuel_refills/1.json
  def show
    @fuel_refill = FuelRefill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fuel_refill }
    end
  end

  # GET /fuel_refills/new
  # GET /fuel_refills/new.json
  def new
    @fuel_refill = FuelRefill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fuel_refill }
    end
  end

  # GET /fuel_refills/1/edit
  def edit
    @fuel_refill = FuelRefill.find(params[:id])
  end

  # POST /fuel_refills
  # POST /fuel_refills.json
  def create
    @fuel_refill = FuelRefill.new(params[:fuel_refill])

    respond_to do |format|
      if @fuel_refill.save
        format.html { redirect_to @fuel_refill, notice: 'Fuel refill was successfully created.' }
        format.json { render json: @fuel_refill, status: :created, location: @fuel_refill }
      else
        format.html { render action: "new" }
        format.json { render json: @fuel_refill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fuel_refills/1
  # PUT /fuel_refills/1.json
  def update
    @fuel_refill = FuelRefill.find(params[:id])

    respond_to do |format|
      if @fuel_refill.update_attributes(params[:fuel_refill])
        format.html { redirect_to @fuel_refill, notice: 'Fuel refill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fuel_refill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_refills/1
  # DELETE /fuel_refills/1.json
  def destroy
    @fuel_refill = FuelRefill.find(params[:id])
    @fuel_refill.destroy

    respond_to do |format|
      format.html { redirect_to fuel_refills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fuel_refills_helper.rb
module FuelRefillsHelper
end

app/views/fuel_refills/_form.html.erb
<%= form_for(@fuel_refill) do |f| %>
  <% if @fuel_refill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fuel_refill.errors.count, "error") %> prohibited this fuel_refill from being saved:</h2>

      <ul>
      <% @fuel_refill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vehicle_number %><br />
    <%= f.text_field :vehicle_number %>
  </div>
  <div class="field">
    <%= f.label :station %><br />
    <%= f.number_field :station %>
  </div>
  <div class="field">
    <%= f.label :litres %><br />
    <%= f.text_field :litres %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :receipt_number %><br />
    <%= f.text_field :receipt_number %>
  </div>
  <div class="field">
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br />
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :SKIP_RAILS_ADMIN_INITIALIZER=false %><br />
    <%= f.text_field :SKIP_RAILS_ADMIN_INITIALIZER=false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fuel_refills/edit.html.erb
<h1>Editing fuel_refill</h1>

<%= render 'form' %>

<%= link_to 'Show', @fuel_refill %> |
<%= link_to 'Back', fuel_refills_path %>

app/views/fuel_refills/index.html.erb
<h1>Listing fuel_refills</h1>

<table>
  <tr>
    <th>Vehicle number</th>
    <th>Station</th>
    <th>Litres</th>
    <th>Price</th>
    <th>Amount</th>
    <th>Receipt number</th>
    <th>Card number</th>
    <th>Account</th>
    <th>Skip rails admin initializer=false</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fuel_refills.each do |fuel_refill| %>
  <tr>
    <td><%= fuel_refill.vehicle_number %></td>
    <td><%= fuel_refill.station %></td>
    <td><%= fuel_refill.litres %></td>
    <td><%= fuel_refill.price %></td>
    <td><%= fuel_refill.amount %></td>
    <td><%= fuel_refill.receipt_number %></td>
    <td><%= fuel_refill.card_number %></td>
    <td><%= fuel_refill.account_id %></td>
    <td><%= fuel_refill.SKIP_RAILS_ADMIN_INITIALIZER=false %></td>
    <td><%= link_to 'Show', fuel_refill %></td>
    <td><%= link_to 'Edit', edit_fuel_refill_path(fuel_refill) %></td>
    <td><%= link_to 'Destroy', fuel_refill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fuel refill', new_fuel_refill_path %>

app/views/fuel_refills/new.html.erb
<h1>New fuel_refill</h1>

<%= render 'form' %>

<%= link_to 'Back', fuel_refills_path %>

app/views/fuel_refills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vehicle number:</b>
  <%= @fuel_refill.vehicle_number %>
</p>

<p>
  <b>Station:</b>
  <%= @fuel_refill.station %>
</p>

<p>
  <b>Litres:</b>
  <%= @fuel_refill.litres %>
</p>

<p>
  <b>Price:</b>
  <%= @fuel_refill.price %>
</p>

<p>
  <b>Amount:</b>
  <%= @fuel_refill.amount %>
</p>

<p>
  <b>Receipt number:</b>
  <%= @fuel_refill.receipt_number %>
</p>

<p>
  <b>Card number:</b>
  <%= @fuel_refill.card_number %>
</p>

<p>
  <b>Account:</b>
  <%= @fuel_refill.account_id %>
</p>

<p>
  <b>Skip rails admin initializer=false:</b>
  <%= @fuel_refill.SKIP_RAILS_ADMIN_INITIALIZER=false %>
</p>


<%= link_to 'Edit', edit_fuel_refill_path(@fuel_refill) %> |
<%= link_to 'Back', fuel_refills_path %>