config/routes.rb
ShakaCompany::Application.routes.draw do
  resources :rent_payments

  get "static_pages/home"

  resources :fuel_payments

  resources :fuel_refills

  resources :accounts

  resources :expenses

  resources :repairs

  resources :jobs

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/job.rb
class Job < ActiveRecord::Base
  
  attr_accessible :allowance, :amount, :client, :days, :departure_date, :document_number, :change_of_route, :driver_name, :fuel, :job_amount, :job_date, :job_details, :job_rate, :previous_route, :price_per_litre, :receipt_number, :route_given, :station, :vehicle_number, :weight_in_tons
  validates :driver_name, :vehicle_number, :job_details, :presence => true
  has_paper_trail
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :driver_name %><br />
    <%= f.text_field :driver_name %>
  </div>
  <div class="field">
    <%= f.label :vehicle_number %><br />
    <%= f.text_field :vehicle_number %>
  </div>
  <div class="field">
    <%= f.label :previous_route %><br />
    <%= f.text_field :previous_route %>
  </div>
  <div class="field">
    <%= f.label :days %><br />
    <%= f.number_field :days %>
  </div>
  <div class="field">
    <%= f.label :fuel %><br />
    <%= f.text_field :fuel %>
  </div>
  <div class="field">
    <%= f.label :price_per_litre %><br />
    <%= f.number_field :price_per_litre %>
  </div>
  <div class="field">
    <%= f.label :receipt_number %><br />
    <%= f.text_field :receipt_number %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :fuel_payment_method %><br />
    <%= f.text_field :fuel_payment_method %>
  </div>
  <div class="field">
    <%= f.label :station %><br />
    <%= f.text_field :station %>
  </div>
  <div class="field">
    <%= f.label :route_given %><br />
    <%= f.text_field :route_given %>
  </div>
  <div class="field">
    <%= f.label :departure_date %><br />
    <%= f.date_select :departure_date %>
  </div>
  <div class="field">
    <%= f.label :change_of_route %><br />
    <%= f.check_box :change_of_route %>
  </div>
  <div class="field">
    <%= f.label :allowance %><br />
    <%= f.number_field :allowance %>
  </div>
  <div class="field">
    <%= f.label :job_date %><br />
    <%= f.date_select :job_date %>
  </div>
  <div class="field">
    <%= f.label :document_number %><br />
    <%= f.text_field :document_number %>
  </div>
  <div class="field">
    <%= f.label :job_details %><br />
    <%= f.text_field :job_details %>
  </div>
  <div class="field">
    <%= f.label :weight_in_tons %><br />
    <%= f.text_field :weight_in_tons %>
  </div>
  <div class="field">
    <%= f.label :job_rate %><br />
    <%= f.number_field :job_rate %>
  </div>
  <div class="field">
    <%= f.label :job_amount %><br />
    <%= f.number_field :job_amount %>
  </div>
  <div class="field">
    <%= f.label :job_payment_method %><br />
    <%= f.text_field :job_payment_method %>
  </div>
  <div class="field">
    <%= f.label :client %><br />
    <%= f.text_field :client %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Driver name</th>
    <th>Vehicle number</th>
    <th>Previous route</th>
    <th>Days</th>
    <th>Fuel</th>
    <th>Price per litre</th>
    <th>Receipt number</th>
    <th>Amount</th>
    <th>Fuel payment method</th>
    <th>Station</th>
    <th>Route given</th>
    <th>Departure date</th>
    <th>Change of route</th>
    <th>Allowance</th>
    <th>Job date</th>
    <th>Document number</th>
    <th>Job details</th>
    <th>Weight in tons</th>
    <th>Job rate</th>
    <th>Job amount</th>
    <th>Job payment method</th>
    <th>Client</th>
    <th>Skip rails admin initializer=false</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.driver_name %></td>
    <td><%= job.vehicle_number %></td>
    <td><%= job.previous_route %></td>
    <td><%= job.days %></td>
    <td><%= job.fuel %></td>
    <td><%= job.price_per_litre %></td>
    <td><%= job.receipt_number %></td>
    <td><%= job.amount %></td>
    <td><%= job.fuel_payment_method %></td>
    <td><%= job.station %></td>
    <td><%= job.route_given %></td>
    <td><%= job.departure_date %></td>
    <td><%= job.change_of_route %></td>
    <td><%= job.allowance %></td>
    <td><%= job.job_date %></td>
    <td><%= job.document_number %></td>
    <td><%= job.job_details %></td>
    <td><%= job.weight_in_tons %></td>
    <td><%= job.job_rate %></td>
    <td><%= job.job_amount %></td>
    <td><%= job.job_payment_method %></td>
    <td><%= job.client %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Driver name:</b>
  <%= @job.driver_name %>
</p>

<p>
  <b>Vehicle number:</b>
  <%= @job.vehicle_number %>
</p>

<p>
  <b>Previous route:</b>
  <%= @job.previous_route %>
</p>

<p>
  <b>Days:</b>
  <%= @job.days %>
</p>

<p>
  <b>Fuel:</b>
  <%= @job.fuel %>
</p>

<p>
  <b>Price per litre:</b>
  <%= @job.price_per_litre %>
</p>

<p>
  <b>Receipt number:</b>
  <%= @job.receipt_number %>
</p>

<p>
  <b>Amount:</b>
  <%= @job.amount %>
</p>

<p>
  <b>Fuel payment method:</b>
  <%= @job.fuel_payment_method %>
</p>

<p>
  <b>Station:</b>
  <%= @job.station %>
</p>

<p>
  <b>Route given:</b>
  <%= @job.route_given %>
</p>

<p>
  <b>Departure date:</b>
  <%= @job.departure_date %>
</p>

<p>
  <b>Change of route:</b>
  <%= @job.change_of_route %>
</p>

<p>
  <b>Allowance:</b>
  <%= @job.allowance %>
</p>

<p>
  <b>Job date:</b>
  <%= @job.job_date %>
</p>

<p>
  <b>Document number:</b>
  <%= @job.document_number %>
</p>

<p>
  <b>Job details:</b>
  <%= @job.job_details %>
</p>

<p>
  <b>Weight in tons:</b>
  <%= @job.weight_in_tons %>
</p>

<p>
  <b>Job rate:</b>
  <%= @job.job_rate %>
</p>

<p>
  <b>Job amount:</b>
  <%= @job.job_amount %>
</p>

<p>
  <b>Job payment method:</b>
  <%= @job.job_payment_method %>
</p>

<p>
  <b>Client:</b>
  <%= @job.client %>
</p>



<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>