config/routes.rb
ShakaCompany::Application.routes.draw do
  resources :rent_payments

  get "static_pages/home"

  resources :fuel_payments

  resources :fuel_refills

  resources :accounts

  resources :expenses

  resources :repairs

  resources :jobs

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/fuel_payment.rb
class FuelPayment < ActiveRecord::Base
  resourcify
  attr_accessible  :account_id, :amount_paid, :balance_amount, :period_end, :period_start, :receipt_number, :station
  has_paper_trail
end

app/controllers/fuel_payments_controller.rb
class FuelPaymentsController < ApplicationController
  # GET /fuel_payments
  # GET /fuel_payments.json
  def index
    @fuel_payments = FuelPayment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fuel_payments }
    end
  end

  # GET /fuel_payments/1
  # GET /fuel_payments/1.json
  def show
    @fuel_payment = FuelPayment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fuel_payment }
    end
  end

  # GET /fuel_payments/new
  # GET /fuel_payments/new.json
  def new
    @fuel_payment = FuelPayment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fuel_payment }
    end
  end

  # GET /fuel_payments/1/edit
  def edit
    @fuel_payment = FuelPayment.find(params[:id])
  end

  # POST /fuel_payments
  # POST /fuel_payments.json
  def create
    @fuel_payment = FuelPayment.new(params[:fuel_payment])

    respond_to do |format|
      if @fuel_payment.save
        format.html { redirect_to @fuel_payment, notice: 'Fuel payment was successfully created.' }
        format.json { render json: @fuel_payment, status: :created, location: @fuel_payment }
      else
        format.html { render action: "new" }
        format.json { render json: @fuel_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fuel_payments/1
  # PUT /fuel_payments/1.json
  def update
    @fuel_payment = FuelPayment.find(params[:id])

    respond_to do |format|
      if @fuel_payment.update_attributes(params[:fuel_payment])
        format.html { redirect_to @fuel_payment, notice: 'Fuel payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fuel_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_payments/1
  # DELETE /fuel_payments/1.json
  def destroy
    @fuel_payment = FuelPayment.find(params[:id])
    @fuel_payment.destroy

    respond_to do |format|
      format.html { redirect_to fuel_payments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fuel_payments_helper.rb
module FuelPaymentsHelper
end

app/views/fuel_payments/_form.html.erb
<%= form_for(@fuel_payment) do |f| %>
  <% if @fuel_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fuel_payment.errors.count, "error") %> prohibited this fuel_payment from being saved:</h2>

      <ul>
      <% @fuel_payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :station %><br />
    <%= f.number_field :station %>
  </div>
  <div class="field">
    <%= f.label :period_start %><br />
    <%= f.date_select :period_start %>
  </div>
  <div class="field">
    <%= f.label :period_end %><br />
    <%= f.date_select :period_end %>
  </div>
  <div class="field">
    <%= f.label :amount_paid %><br />
    <%= f.number_field :amount_paid %>
  </div>
  <div class="field">
    <%= f.label :balance_amount %><br />
    <%= f.number_field :balance_amount %>
  </div>
  <div class="field">
    <%= f.label :receipt_number %><br />
    <%= f.text_field :receipt_number %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br />
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :SKIP_RAILS_ADMIN_INITIALIZER=false %><br />
    <%= f.text_field :SKIP_RAILS_ADMIN_INITIALIZER=false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fuel_payments/edit.html.erb
<h1>Editing fuel_payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @fuel_payment %> |
<%= link_to 'Back', fuel_payments_path %>

app/views/fuel_payments/index.html.erb
<h1>Listing fuel_payments</h1>

<table>
  <tr>
    <th>Station</th>
    <th>Period start</th>
    <th>Period end</th>
    <th>Amount paid</th>
    <th>Balance amount</th>
    <th>Receipt number</th>
    <th>Account</th>
    <th>Skip rails admin initializer=false</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fuel_payments.each do |fuel_payment| %>
  <tr>
    <td><%= fuel_payment.station %></td>
    <td><%= fuel_payment.period_start %></td>
    <td><%= fuel_payment.period_end %></td>
    <td><%= fuel_payment.amount_paid %></td>
    <td><%= fuel_payment.balance_amount %></td>
    <td><%= fuel_payment.receipt_number %></td>
    <td><%= fuel_payment.account_id %></td>
    <td><%= fuel_payment.SKIP_RAILS_ADMIN_INITIALIZER=false %></td>
    <td><%= link_to 'Show', fuel_payment %></td>
    <td><%= link_to 'Edit', edit_fuel_payment_path(fuel_payment) %></td>
    <td><%= link_to 'Destroy', fuel_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fuel payment', new_fuel_payment_path %>

app/views/fuel_payments/new.html.erb
<h1>New fuel_payment</h1>

<%= render 'form' %>

<%= link_to 'Back', fuel_payments_path %>

app/views/fuel_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Station:</b>
  <%= @fuel_payment.station %>
</p>

<p>
  <b>Period start:</b>
  <%= @fuel_payment.period_start %>
</p>

<p>
  <b>Period end:</b>
  <%= @fuel_payment.period_end %>
</p>

<p>
  <b>Amount paid:</b>
  <%= @fuel_payment.amount_paid %>
</p>

<p>
  <b>Balance amount:</b>
  <%= @fuel_payment.balance_amount %>
</p>

<p>
  <b>Receipt number:</b>
  <%= @fuel_payment.receipt_number %>
</p>

<p>
  <b>Account:</b>
  <%= @fuel_payment.account_id %>
</p>

<p>
  <b>Skip rails admin initializer=false:</b>
  <%= @fuel_payment.SKIP_RAILS_ADMIN_INITIALIZER=false %>
</p>


<%= link_to 'Edit', edit_fuel_payment_path(@fuel_payment) %> |
<%= link_to 'Back', fuel_payments_path %>