config/routes.rb
ShakaCompany::Application.routes.draw do
  resources :rent_payments

  get "static_pages/home"

  resources :fuel_payments

  resources :fuel_refills

  resources :accounts

  resources :expenses

  resources :repairs

  resources :jobs

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  resourcify
  attr_accessible :amount, :details_of_service, :garage, :invoice_number, :vehicle_number
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repairs }
    end
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
    @repair = Repair.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repair }
    end
  end

  # GET /repairs/new
  # GET /repairs/new.json
  def new
    @repair = Repair.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repair }
    end
  end

  # GET /repairs/1/edit
  def edit
    @repair = Repair.find(params[:id])
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @repair = Repair.new(params[:repair])

    respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: 'Repair was successfully created.' }
        format.json { render json: @repair, status: :created, location: @repair }
      else
        format.html { render action: "new" }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repairs/1
  # PUT /repairs/1.json
  def update
    @repair = Repair.find(params[:id])

    respond_to do |format|
      if @repair.update_attributes(params[:repair])
        format.html { redirect_to @repair, notice: 'Repair was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair = Repair.find(params[:id])
    @repair.destroy

    respond_to do |format|
      format.html { redirect_to repairs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/repairs/_form.html.erb
<%= form_for(@repair) do |f| %>
  <% if @repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% @repair.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :garage %><br />
    <%= f.text_field :garage %>
  </div>
  <div class="field">
    <%= f.label :details_of_service %><br />
    <%= f.text_field :details_of_service %>
  </div>
  <div class="field">
    <%= f.label :vehicle_number %><br />
    <%= f.text_field :vehicle_number %>
  </div>
  <div class="field">
    <%= f.label :invoice_number %><br />
    <%= f.text_field :invoice_number %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repairs/edit.html.erb
<h1>Editing repair</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair %> |
<%= link_to 'Back', repairs_path %>

app/views/repairs/index.html.erb
<h1>Listing repairs</h1>

<table>
  <tr>
    <th>Garage</th>
    <th>Details of service</th>
    <th>Vehicle number</th>
    <th>Invoice number</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repairs.each do |repair| %>
  <tr>
    <td><%= repair.garage %></td>
    <td><%= repair.details_of_service %></td>
    <td><%= repair.vehicle_number %></td>
    <td><%= repair.invoice_number %></td>
    <td><%= repair.amount %></td>
    <td><%= link_to 'Show', repair %></td>
    <td><%= link_to 'Edit', edit_repair_path(repair) %></td>
    <td><%= link_to 'Destroy', repair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repair', new_repair_path %>

app/views/repairs/new.html.erb
<h1>New repair</h1>

<%= render 'form' %>

<%= link_to 'Back', repairs_path %>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Garage:</b>
  <%= @repair.garage %>
</p>

<p>
  <b>Details of service:</b>
  <%= @repair.details_of_service %>
</p>

<p>
  <b>Vehicle number:</b>
  <%= @repair.vehicle_number %>
</p>

<p>
  <b>Invoice number:</b>
  <%= @repair.invoice_number %>
</p>

<p>
  <b>Amount:</b>
  <%= @repair.amount %>
</p>


<%= link_to 'Edit', edit_repair_path(@repair) %> |
<%= link_to 'Back', repairs_path %>